import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css"; // pastikan ini diimpor juga

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Task Apps",
  description: "Generated by create Luzpell",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="h-full bg-gray-900">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased h-screen overflow-hidden flex flex-col bg-gray-900`}
      >
        <ToastContainer />
        {/* Navbar yang fixed */}
        <Navbar className="fixed top-0 left-0 right-0 z-50 bg-gray-800" />
        {/* Konten utama dengan padding atas */}
        <main className="flex-1 overflow-hidden pt-5 pb-[80px]">
          {/* Konten di sini */}
          {children}
        </main>
      </body>
    </html>
  );
}
